// <auto-generated />
using Labb3API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb3API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240527105351_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SUT23TeknikButikModels.Connections.InterestLinks", b =>
                {
                    b.Property<int>("LinkID")
                        .HasColumnType("int");

                    b.Property<int>("InterestID")
                        .HasColumnType("int");

                    b.Property<int>("InterestLinkID")
                        .HasColumnType("int");

                    b.HasKey("LinkID", "InterestID");

                    b.HasIndex("InterestID");

                    b.ToTable("InterestLinks");

                    b.HasData(
                        new
                        {
                            LinkID = 1,
                            InterestID = 1,
                            InterestLinkID = 0
                        },
                        new
                        {
                            LinkID = 2,
                            InterestID = 1,
                            InterestLinkID = 0
                        });
                });

            modelBuilder.Entity("SUT23TeknikButikModels.Connections.PersonInterests", b =>
                {
                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<int>("InterestID")
                        .HasColumnType("int");

                    b.Property<int>("PersonInterestsID")
                        .HasColumnType("int");

                    b.HasKey("PersonID", "InterestID");

                    b.HasIndex("InterestID");

                    b.ToTable("PersonInterests");

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            InterestID = 1,
                            PersonInterestsID = 0
                        },
                        new
                        {
                            PersonID = 1,
                            InterestID = 2,
                            PersonInterestsID = 0
                        },
                        new
                        {
                            PersonID = 2,
                            InterestID = 1,
                            PersonInterestsID = 0
                        });
                });

            modelBuilder.Entity("SUT23TeknikButikModels.Interest", b =>
                {
                    b.Property<int>("InterestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestID"));

                    b.Property<string>("InterestTitle")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("InterestsDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InterestID");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestID = 1,
                            InterestTitle = "Surfing",
                            InterestsDescription = "Väldigt kul, vatten"
                        },
                        new
                        {
                            InterestID = 2,
                            InterestTitle = "Matlagning",
                            InterestsDescription = "Väldigt kul, ingredienser och grejer"
                        },
                        new
                        {
                            InterestID = 3,
                            InterestTitle = "Datorspel",
                            InterestsDescription = "Väldigt kul, dator"
                        });
                });

            modelBuilder.Entity("SUT23TeknikButikModels.Link", b =>
                {
                    b.Property<int>("LinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkID"));

                    b.Property<string>("LinkSite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinkID");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            LinkID = 1,
                            LinkSite = "https://magnusandfriends.se/sv/den-kompletta-surf-guiden/?gad_source=1&gclid=Cj0KCQjwjLGyBhCYARIsAPqTz18D50Ic8DNB1AC5G4p9x7sPzTO-06fC7Xs3faEYufv1PEYx2y0ez-gaAn4VEALw_wcB"
                        },
                        new
                        {
                            LinkID = 2,
                            LinkSite = "https://www.lapoint.se/?gad_source=1&gclid=Cj0KCQjw3tCyBhDBARIsAEY0XNkNh8aYEYYJ5v36jgFFx0-Zr2-ZBaodHOYuDRXhyjkWp-uxJCTRI94aAoocEALw_wcB"
                        });
                });

            modelBuilder.Entity("SUT23TeknikButikModels.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<double>("PhoneNumber")
                        .HasColumnType("float");

                    b.HasKey("PersonID");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            FirstName = "Adam",
                            LastName = "Andersson",
                            PhoneNumber = 42552525.0
                        },
                        new
                        {
                            PersonID = 2,
                            FirstName = "Eva",
                            LastName = "Johansson",
                            PhoneNumber = 731234567.0
                        });
                });

            modelBuilder.Entity("SUT23TeknikButikModels.Connections.InterestLinks", b =>
                {
                    b.HasOne("SUT23TeknikButikModels.Interest", "Interest")
                        .WithMany("InterestLinks")
                        .HasForeignKey("InterestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SUT23TeknikButikModels.Link", "Link")
                        .WithMany("InterestLinks")
                        .HasForeignKey("LinkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Link");
                });

            modelBuilder.Entity("SUT23TeknikButikModels.Connections.PersonInterests", b =>
                {
                    b.HasOne("SUT23TeknikButikModels.Interest", "Interests")
                        .WithMany("PersonInterests")
                        .HasForeignKey("InterestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SUT23TeknikButikModels.Person", "Person")
                        .WithMany("PersonInterests")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interests");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SUT23TeknikButikModels.Interest", b =>
                {
                    b.Navigation("InterestLinks");

                    b.Navigation("PersonInterests");
                });

            modelBuilder.Entity("SUT23TeknikButikModels.Link", b =>
                {
                    b.Navigation("InterestLinks");
                });

            modelBuilder.Entity("SUT23TeknikButikModels.Person", b =>
                {
                    b.Navigation("PersonInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
